let imageCategories = {
    "ghost": {
        scale: 2,
        images: [
            "p_ghost_ship_normal_01.png",
            "p_ghost_ship_normal_02.png",
            "p_ghost_ship_normal_03.png",
        ],
    },
    "natural": {
        scale: 1.5,
        images: [
            "p_natural_normal_01.png",
            "p_natural_normal_02.png",
            "p_natural_normal_03.png",
            "p_natural_normal_04.png",
            "p_natural_normal_05.png",
            "p_natural_normal_06.png",
            "p_natural_normal_07.png",
            "p_natural_normal_08.png",
            "p_natural_normal_11.png",
            "p_natural_normal_12.png",
        ],
    },
    "rowboat": {
        scale: 0.6,
        images: [
            "p_rowboat_normal_01.png",
            "p_rowboat_normal_02.png",
            "p_rowboat_normal_03.png",
            "p_rowboat_normal_04.png",
            "p_rowboat_normal_05.png",
            "p_rowboat_normal_06.png",
            "p_rowboat_normal_07.png",
            "p_rowboat_normal_08.png",
            "p_rowboat_normal_09.png",
            "p_rowboat_normal_10.png",
            "p_rowboat_normal_11.png",
            "p_rowboat_normal_12.png",
            "p_rowboat_normal_13.png",
            "p_rowboat_normal_14.png",
        ],
    },
    "beast": {
        scale: 1.1,
        images: [
            "p_sea_beast_normal_01.png",
            "p_sea_beast_normal_02.png",
            "p_sea_beast_normal_03.png",
            "p_sea_beast_normal_04.png",
            "p_sea_beast_normal_05.png",
            "p_sea_beast_normal_06.png",
            "p_sea_beast_normal_07.png",
            "p_sea_beast_normal_08.png",
            "p_sea_beast_normal_09.png",
            "p_sea_beast_normal_10.png",
            "p_sea_beast_normal_11.png",
            "p_sea_beast_normal_12.png",
            "p_sea_beast_normal_13.png",
            "p_sea_beast_normal_14.png",
        ],
    },
    "ship": {
        scale: 2,
        images: [
        "p_ship_normal_01.png",
        "p_ship_normal_03.png",
        "p_ship_normal_05.png",
        "p_ship_normal_06.png",
        "p_ship_normal_07.png",
        "p_ship_normal_08.png",
        "p_ship_normal_09.png",
        "p_ship_normal_10.png",
        "p_ship_normal_11.png",
        "p_ship_normal_12.png",
        "p_ship_normal_13.png",
        "p_ship_normal_14.png",
        "p_ship_normal_15.png",
        "p_ship_normal_16.png",
        "p_ship_normal_17.png",
        "p_ship_normal_18.png",
        "p_ship_normal_19.png",
        "p_ship_normal_20.png",
        "p_ship_normal_21.png",
        "p_ship_normal_22.png",
        "p_ship_normal_23.png",
        "p_ship_normal_24.png",
        "p_ship_normal_25.png",
        "p_ship_normal_26.png",
        "p_ship_normal_27.png",
        "p_ship_normal_28.png",
        "p_ship_normal_29.png",
        "p_ship_normal_30.png",
        "p_ship_normal_31.png",
        "p_ship_normal_32.png",
        "p_ship_normal_33.png",
        "p_ship_normal_34.png",
        "p_ship_normal_35.png",
        "p_ship_normal_36.png",
        ],
    },
    "wreck": {
        scale: 1.5,
        images: [
            "p_wreckssunken_normal_01.png",
            "p_wreckssunken_normal_02.png",
            "p_wreckssunken_normal_03.png",
            "p_wreckssunken_normal_04.png",
            "p_wreckssunken_normal_05.png",
            "p_wreckssunken_normal_06.png",
            "p_wreckssunken_normal_07.png",
            "p_wreckssunken_normal_08.png",
            "p_wreckssunken_normal_09.png",
            "p_wreckssunken_normal_10.png",
            "p_wreckssunken_normal_11.png",
            "p_wreckssunken_normal_12.png",
            "p_wreckssunken_normal_13.png",
            "p_wreckssunken_normal_14.png",
            "p_wreckssunken_normal_15.png",
            "p_wreckssunken_normal_16.png",
            "p_wreckssunken_normal_17.png",
            "p_wreckssunken_normal_18.png",
            "p_wreckssunken_normal_19.png",
            "p_wreckssunken_normal_20.png",
            "p_wreckssunken_normal_21.png",
            "p_wreckssunken_normal_22.png"
        ],
    }
};

let music = [
  "Drunken Sailor.mp3",
  "Land Lubber.mp3",
  "The Sailor's Hornpipe.mp3",
  "Haul Away The Bowline.mp3",
  "Nauticalities.mp3",
  "Shiver Me Timbers.mp3",
  "The Hornpipe.mp3"
];

let wavesSound = "soothing-ocean-waves-372489.mp3";

let unusedImages = [
    "p_natural_normal_09.png",
    "p_natural_normal_10.png",
    "p_ship_normal_02.png",
    "p_flyingship_normal_06.png",
    "p_flyingship_normal_07.png",
    "p_ship_normal_04.png",
];

let unusedCategories = {
    "flying": {
        scale: 1.5,
        images: [
            "p_flyingship_normal_01.png",
            "p_flyingship_normal_02.png",
            "p_flyingship_normal_03.png",
            "p_flyingship_normal_04.png",
            "p_flyingship_normal_05.png",
        ],
    },
};
